package com.kapilguru.student.webinar.webinarDetails.model

import com.google.gson.annotations.SerializedName

data class WebinarDetailsResData(
    @SerializedName("end_date") val endDate: String = "",
    @SerializedName("code") var code: String? = null,
    @SerializedName("about") val about: String = "",
    @SerializedName("video") val video: String = "",
    @SerializedName("title") val title: String = "",
    @SerializedName("rejected_by") val rejectedBy: Int = 0,
    @SerializedName("webinar_video") var webinarVideo: String? = null,
    @SerializedName("roomname") val roomname: String? = null,
    @SerializedName("rejected_reason") val rejectedReason: String? = null,
    @SerializedName("duration_hrs") val durationHrs: Int = 0,
    @SerializedName("price") val price: Double? = 0.0,
    @SerializedName("no_of_attendees") val noOfAttendees: Int = 0,
    @SerializedName("requested_date") val requestedDate: String = "",
    @SerializedName("request_money_id") val requestMoneyId: Int = 0,
    @SerializedName("is_rejected") val isRejected: Int = 0,
    @SerializedName("registered_no_of_attendees") val registeredNoOfAttendees: Int = 0,
    @SerializedName("videomeet_host_id") val videomeetHostId: Int = 0,
    @SerializedName("id") val id: Int = 0,
    @SerializedName("is_paid") val isPaid: Int = 0,
    @SerializedName("trainer_id") val trainerId: Int = 0,
    @SerializedName("start_date") val startDate: String = "",
    @SerializedName("course_id") val courseId: Int = 0,
    @SerializedName("image") val image: String = "",
    @SerializedName("is_active") val isActive: Int = 0,
    @SerializedName("languages") val languages: String = "",
    @SerializedName("speaker_name") val speakerName: String = "",
    @SerializedName("end_time") val endTime: String = "",
    @SerializedName("is_conducted") val isConducted: Int = 0,
    @SerializedName("room_pass") val roomPass: String? = null,
    @SerializedName("modified_date") val modifiedDate: String = "",
    @SerializedName("is_verified") val isVerified: Int = 0,
    @SerializedName("created_by") val createdBy: Int = 0,
    @SerializedName("is_requested") val isRequested: Int = 0,
    @SerializedName("start_time") val startTime: String = "",
    @SerializedName("verified_by") val verifiedBy: Int = 0,
    @SerializedName("confrenceid") val confrenceid: Int = 0,
    @SerializedName("duration_days") val durationDays: Int = 0,
    @SerializedName("modified_by") val modifiedBy: String? = null,
    @SerializedName("paid_money_id") val paidMoneyId: Int = 0,
    @SerializedName("topic") val topic: String? = null,
    @SerializedName("created_date") val createdDate: String = "",
    @SerializedName("paid_date") val paidDate: String? = null,
    @SerializedName("status") val status: String = "",
    @SerializedName("db_ctime") val dbCTime: String = "")